name: Deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Create deployment

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps: 
       - uses: actions/checkout@v1

       - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: production
          initial_status: success

