name: Deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Create deployment

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v1

      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: production
          state: success

